trigger:
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  displayName: Build
  jobs:
  - job: BuildJob
    displayName: Build Job
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '22.x'
      displayName: Use Node.js 22

    - script: npm install
      displayName: Install dependencies

    - script: npm run build
      displayName: Build app

- stage: Deploy_Prod
  displayName: Deploy to Production VM
  dependsOn: Build
  condition: succeeded()
  jobs:
  - job: Deploy
    displayName: Deploy
    steps:
    - task: SSH@0
      displayName: Deploy on genznext VM
      inputs:
        sshEndpoint: 'genznext-prod-vm-ssh'
        runOptions: 'commands'
        commands: |
          bash -lc '
            set -e
            echo "===== DEPLOY START ====="
            whoami
            cd /home/Mithilesh23/expert-learning
            pwd
            git status
            git checkout main
            git pull origin main
            npm install
            npm run build
            pm2 restart genznext
            pm2 save
            echo "===== DEPLOY DONE ====="
          '
        readyTimeout: '20000'