import {
  Award, Bot, Briefcase, Clock3, Code2,
  FolderKanban, GraduationCap, Layers,
  Server, Shield, Sparkles, Terminal,
  Users2, Zap,
} from "lucide-react";
import { ProgramPageLayout, type ProgramPageData } from "@/components/programs/program-page-layout";
import { buildMetadata } from "@/lib/metadata";

export const metadata = buildMetadata({
  title: "Microsoft Cloud & AI DevOps Master Program | GenZNext",
  description:
    "24-week job-ready program: Azure Administration (AZ-104) → Azure DevOps Engineering (AZ-400) → AI-Powered DevSecOps. Kubernetes, Terraform, GitHub Copilot & Microsoft Sentinel. Live mentorship, 15+ projects, placement support.",
  path: "/programs/microsoft-cloud-ai-devops-master",
});

const data: ProgramPageData = {
  badge: "Azure + DevOps + AI Track",
  badgeColor: "border-[#FED7AA] bg-[#FFF7ED] text-[#9A3412]",
  tag: "🔥 Most In-Demand 2025",
  tagline: "Become a Job-Ready Azure Cloud, DevOps & AI Operations Engineer",
  title: "Microsoft Cloud & AI DevOps Master Program",
  description:
    "A 24-week, job-ready program that takes you from Azure fundamentals to AI-powered DevSecOps engineering. Master AZ-104, AZ-400, Kubernetes, Terraform, GitHub Copilot and Microsoft Sentinel — with real capstone projects, live mentor sessions and placement support at every phase.",
  chips: [
    "Live Instructor-Led Sessions",
    "AZ-104 Azure Admin Prep",
    "AZ-400 DevOps Engineer Prep",
    "Kubernetes & AKS",
    "Terraform IaC",
    "GitHub Copilot for DevOps",
    "Microsoft Sentinel (SIEM)",
    "LMS Access",
    "Placement Support",
  ],
  stats: [
    { icon: Clock3,       label: "24 Weeks" },
    { icon: Layers,       label: "3 Phases" },
    { icon: FolderKanban, label: "15+ Projects" },
    { icon: Award,        label: "AZ-104 + AZ-400" },
  ],
  price:         "Rs. 34,999",
  originalPrice: "Rs. 74,999",
  priceLabel:    "53% off · No-cost EMI available",
  enrollSlug:    "microsoft-cloud-ai-devops-master-program",
  enrollFeatures: [
    { icon: Clock3,       text: "24 Weeks (6 Months)" },
    { icon: GraduationCap,text: "Beginner to Advanced" },
    { icon: FolderKanban, text: "15+ Real-World Projects" },
    { icon: Award,        text: "AZ-104 + AZ-400 Exam Prep" },
    { icon: Shield,       text: "AI-Powered DevSecOps" },
    { icon: Users2,       text: "Live Sessions + LMS Access for Life" },
  ],
  roadmap: [
    "AZ-104 Azure Administrator",
    "AZ-400 DevOps Engineer Expert",
    "AI-Powered DevSecOps",
    "Platform Engineer / SRE",
  ],

  /* ═══════════════════════════════════════════════════════════
     PHASE 1 — AZ-104 Azure Administration (8 Weeks)
  ═══════════════════════════════════════════════════════════ */
  phases: [
    {
      label: "Phase 1",
      title: "Azure Administration — AZ-104",
      duration: "8 Weeks",
      cert: "AZ-104",
      color: "bg-[#EFF6FF] text-[#1E40AF] border-[#BFDBFE]",
      icon: Server,
      objective:
        "Build a strong, enterprise-grade foundation in Microsoft Azure. You will learn to deploy, secure, monitor and govern cloud infrastructure the way production teams do — not just pass an exam. Every module has a hands-on lab that produces a real deliverable.",
      modules: [
        {
          title: "Cloud Fundamentals & Azure Global Architecture",
          week: "Week 1",
          topics: [
            "Cloud computing service models: IaaS, PaaS, SaaS, FaaS",
            "Public, Private, Hybrid and Multi-Cloud strategies",
            "Azure Global Infrastructure: 60+ Regions, Availability Zones, Edge Zones",
            "Azure Sovereign Regions: Government, China, Germany",
            "Azure Subscription hierarchy: Tenant → Management Group → Subscription → Resource Group → Resource",
            "Azure Resource Manager (ARM): control plane, RBAC and lock model",
            "Cloud Adoption Framework (CAF): Strategy, Plan, Ready, Adopt, Govern, Manage",
            "Azure Well-Architected Framework: Reliability, Security, Cost Optimization, Operational Excellence, Performance",
            "Azure Portal, CLI (az), PowerShell (Az module) and REST API",
            "Azure Cloud Shell and local development toolchain setup",
          ],
          tools: ["Azure Portal", "Azure CLI", "Azure PowerShell", "Cloud Shell"],
          lab: "Provision a Resource Group hierarchy (3 environments: dev/staging/prod), apply Management Group policies and explore Cost Management",
          labOutcome: "A tagged, policy-compliant 3-environment Azure structure ready for team use",
        },
        {
          title: "Microsoft Entra ID & Identity Management",
          week: "Week 2",
          topics: [
            "Microsoft Entra ID (Azure AD): Directory structure, Tenants and B2B/B2C",
            "Users: creation, bulk import via CSV, UPN vs ObjectID",
            "Groups: Security vs Microsoft 365, dynamic membership rules",
            "Service Principals and App Registrations for app identity",
            "Role-Based Access Control (RBAC): Owner, Contributor, Reader and 80+ built-in roles",
            "Custom RBAC roles: JSON definition, scope levels (subscription, RG, resource)",
            "Conditional Access Policies: IP ranges, device compliance, sign-in risk",
            "Multi-Factor Authentication (MFA): TOTP, SMS, Microsoft Authenticator app",
            "Privileged Identity Management (PIM): JIT access, approval workflows, audit logs",
            "Identity Protection: risk-based policies, risky sign-in remediation",
            "Entra ID Connect: password hash sync, pass-through auth, federation",
            "Self-Service Password Reset (SSPR) and password writeback",
          ],
          tools: ["Entra ID (Azure AD)", "PIM", "Azure AD Connect", "Microsoft Authenticator"],
          lab: "Configure enterprise IAM for a 50-person org: users, groups, MFA, Conditional Access policy for risky locations and PIM for Contributor access",
          labOutcome: "Zero-trust identity baseline: no standing admin access, all elevated roles time-bound via PIM",
        },
        {
          title: "Virtual Machines, Compute & High Availability",
          week: "Week 3",
          topics: [
            "VM families: General Purpose (D/B), Compute Optimised (F), Memory Optimised (E/M), Storage Optimised (L), GPU (NC/ND)",
            "VM deployment: portal, CLI, ARM templates and Bicep",
            "VM Image Gallery (Azure Compute Gallery): custom images, versioning, sharing",
            "Managed Disks: Premium SSD, Standard SSD, Standard HDD, Ultra Disk — IOPS and throughput comparison",
            "Disk snapshots, incremental backups and cross-region copy",
            "Availability Sets: fault domains vs update domains (99.95% SLA)",
            "Availability Zones: zone-redundant deployments (99.99% SLA)",
            "Virtual Machine Scale Sets (VMSS): custom scaling rules, mixed instances, Spot VMs",
            "Azure Bastion: browser-based RDP/SSH — no public IP required",
            "Just-In-Time (JIT) VM Access via Defender for Cloud",
            "Azure VM Guest Agent, extensions and custom script extension",
            "Azure Recovery Services Vault: VM backup policy, instant restore, cross-region restore",
          ],
          tools: ["Azure VMs", "VMSS", "Azure Bastion", "Recovery Services Vault", "Azure Compute Gallery"],
          lab: "Deploy a 3-tier app: web VMSS with auto-scale rules (CPU 70%), app VMs in Availability Zones, Azure Bastion for access, and Recovery Services backup with 30-day retention",
          labOutcome: "Highly available, auto-scaling compute tier with zero public SSH/RDP exposure",
        },
        {
          title: "Azure Networking: VNet, NSG, Load Balancing & DNS",
          week: "Week 4",
          topics: [
            "Virtual Network (VNet) design: CIDR planning, subnet segmentation best practices",
            "Network Security Groups (NSG): stateful rules, priority order, effective security rules",
            "Application Security Groups (ASG): tag-based rules for east-west traffic control",
            "Azure Load Balancer (Standard): frontend IP, backend pool, health probes, session persistence",
            "Azure Application Gateway v2: URL-based routing, multi-site hosting, cookie affinity",
            "Azure Web Application Firewall (WAF) on Application Gateway: OWASP 3.2 rule sets",
            "Azure VPN Gateway: site-to-site, point-to-site, IKEv2/OpenVPN",
            "ExpressRoute: dedicated private connectivity (50Mbps–100Gbps), FastPath",
            "VNet Peering: local and global — no gateway transit by default",
            "Azure Private DNS Zones: auto-registration, split-horizon DNS",
            "Azure Traffic Manager: DNS-based global load balancing (priority, weighted, performance, geographic)",
            "Network Watcher: connection monitor, packet capture, next-hop, effective routes",
          ],
          tools: ["Azure VNet", "NSG", "Application Gateway", "Azure Firewall", "Network Watcher", "Private DNS"],
          lab: "Design a hub-spoke network: hub VNet (Azure Firewall, Bastion, VPN Gateway) + 3 spoke VNets (dev/staging/prod) with peering, NSG rules, and Application Gateway with WAF",
          labOutcome: "Enterprise hub-spoke network with zero east-west traffic allowed by default, all traffic inspected through Azure Firewall",
        },
        {
          title: "Azure Storage: Blob, Files, Tables, Queues & Data Protection",
          week: "Week 5",
          topics: [
            "Storage account types: Standard (GPv2) vs Premium (Block Blob, File Shares, Page Blobs)",
            "Redundancy options: LRS, ZRS, GRS, GZRS, RA-GRS — RPO and failover behaviour",
            "Blob storage: Block blobs, Append blobs, Page blobs",
            "Access tiers: Hot (< 30 days), Cool (> 30 days), Cold, Archive (180+ days)",
            "Blob lifecycle management policies: transition and deletion rules",
            "Azure Files: SMB 3.0/NFS 4.1 shares, Azure File Sync for hybrid file servers",
            "Storage security: Storage Firewall, Virtual Network Service Endpoints, Private Endpoints",
            "Shared Access Signatures (SAS): account SAS, service SAS, user delegation SAS",
            "Stored Access Policies: revoke SAS without rotating keys",
            "Encryption: Microsoft-managed keys (MMK), Customer-managed keys (CMK) via Key Vault, Customer-provided keys (CPK)",
            "Azure Data Lake Storage Gen2 (ADLS): hierarchical namespace, ACLs, integration with Synapse/Databricks",
            "Blob versioning, soft delete (blob and container level), immutability policies (WORM)",
          ],
          tools: ["Azure Blob Storage", "Azure Files", "AzCopy", "Azure Storage Explorer", "Key Vault"],
          lab: "Configure a secure data platform: blob with lifecycle policies (hot→cool→archive→delete), Files share with Azure File Sync, CMK encryption via Key Vault, and SAS with stored access policy",
          labOutcome: "GDPR-compliant storage: all data encrypted with customer keys, immutable audit logs, automated lifecycle cost optimization",
        },
        {
          title: "App Services, Containers & Azure Functions",
          week: "Week 6",
          topics: [
            "Azure App Service Plans: Free, Shared, Basic, Standard, Premium, Isolated (ASE)",
            "Web Apps: runtime stacks (.NET, Python, Node, Java, PHP, Ruby), deployment slots",
            "Deployment methods: Git, GitHub Actions, ZIP deploy, FTP, container from ACR",
            "App Service deployment slots: staging, traffic splitting, slot-specific settings",
            "App Service Authentication (EasyAuth): Entra ID, Google, Facebook, GitHub",
            "App Service networking: VNet Integration, Private Endpoints, Hybrid Connections",
            "Azure Container Instances (ACI): quick container deployment, volume mounts, multi-container groups",
            "Azure Container Registry (ACR): geo-replication, webhooks, content trust",
            "Azure Functions: consumption vs Premium vs Dedicated plan",
            "Function triggers: HTTP, Timer, Blob, Queue, Service Bus, Event Grid, Cosmos DB",
            "Durable Functions: orchestrations, activity functions, fan-out/fan-in patterns",
            "Azure Logic Apps: low-code workflow automation, 500+ connectors",
          ],
          tools: ["Azure App Service", "ACR", "Azure Functions", "Logic Apps", "GitHub Actions"],
          lab: "Deploy a Python Flask app to App Service with staging slot (blue-green deployment), set up GitHub Actions CI/CD, configure VNet Integration and auto-scale based on HTTP queue length",
          labOutcome: "Zero-downtime deployment pipeline with automated rollback capability",
        },
        {
          title: "Azure Monitor, Log Analytics & Governance",
          week: "Week 7",
          topics: [
            "Azure Monitor: data sources (metrics, logs, traces, changes, health)",
            "Metrics Explorer: visualisation, splitting, filtering, custom metrics via REST API",
            "Log Analytics Workspace: KQL fundamentals — summarize, join, project, parse, mv-expand",
            "Diagnostic Settings: platform logs, activity log, resource logs routing to LAW/Storage/Event Hub",
            "Application Insights: APM, distributed tracing, availability tests, Smart Detection",
            "Azure Monitor Alerts: metric alerts, log alerts, activity log alerts, smart groups",
            "Action Groups: email, SMS, webhook, Azure Function, Logic App, ITSM integration",
            "Azure Workbooks: interactive reports combining metrics, logs and ARM data",
            "Azure Policy: policy definitions, initiatives, assignments, compliance dashboard",
            "Policy effects: Deny, Audit, Append, Modify, DeployIfNotExists, AuditIfNotExists",
            "Azure Blueprints: version-controlled environment templates (deprecated → use Bicep/Terraform)",
            "Azure Cost Management: cost analysis, budgets with alert thresholds, Advisor recommendations",
          ],
          tools: ["Azure Monitor", "Log Analytics", "KQL", "Application Insights", "Azure Policy"],
          lab: "Build an operations command centre: 25 KQL queries (failed logins, VM restarts, cost anomalies), metric alerts with PagerDuty-style action group, and Azure Policy enforcing tag compliance across all resources",
          labOutcome: "Full observability platform with automated compliance reporting and cost anomaly detection",
        },
        {
          title: "AZ-104 Exam Preparation & Capstone",
          week: "Week 8",
          topics: [
            "AZ-104 exam (updated April 17, 2026): 40–60 questions, new Microsoft Entra ID & Azure Arc content",
            "High-weight domains: Identity (15–20%), Storage (10–15%), Compute (20–25%), Networking (25–30%), Monitoring (10–15%)",
            "Common trap questions: RBAC scope inheritance, NSG stateful behaviour, storage redundancy failover",
            "Hands-on exam simulation: 3 full mock exams (150+ questions)",
            "Weak area revision sessions with mentors",
            "Azure exam voucher guidance and scheduling",
          ],
          tools: ["Microsoft Learn", "AZ-104 Practice Tests", "MeasureUp", "Whizlabs"],
          lab: "Complete 3 timed mock exams (passing score ≥ 700/1000) and fix all gaps identified in the review session",
          labOutcome: "AZ-104 exam-ready with documented study plan and 80%+ mock score",
        },
      ],
      capstone: {
        title: "Phase 1 Capstone — Enterprise Azure Infrastructure",
        deliverables: [
          "Hub-spoke VNet (Azure Firewall + Bastion + VPN Gateway + 3 spoke VNets)",
          "Multi-AZ VMSS with auto-scale and Recovery Services backup",
          "Secure storage: lifecycle policies, CMK encryption, immutable blobs",
          "App Service with blue-green deployment slots and CI/CD via GitHub Actions",
          "Log Analytics workspace: 25+ KQL queries, metric alerts, Azure Policy compliance",
          "Entra ID: MFA, Conditional Access, PIM for all admin roles",
          "Full documentation and architecture diagram (draw.io)",
        ],
      },
    },

    /* ═══════════════════════════════════════════════════════════
       PHASE 2 — AZ-400 Azure DevOps Engineering (8 Weeks)
    ═══════════════════════════════════════════════════════════ */
    {
      label: "Phase 2",
      title: "Azure DevOps Engineering — AZ-400",
      duration: "8 Weeks",
      cert: "AZ-400",
      color: "bg-[#F0FDF4] text-[#166534] border-[#BBF7D0]",
      icon: Zap,
      objective:
        "Master the full DevOps lifecycle on Azure. You will design and implement pipelines, containerise applications, deploy to Kubernetes, automate infrastructure with Terraform, and wire up end-to-end observability — exactly as senior DevOps engineers do in enterprise teams.",
      modules: [
        {
          title: "Git, GitHub & Enterprise Source Control",
          week: "Week 9",
          topics: [
            "Git internals: objects (blob, tree, commit, tag), refs, packfiles",
            "Branching strategies: GitFlow (feature/release/hotfix), GitHub Flow, trunk-based development",
            "Semantic versioning (semver): MAJOR.MINOR.PATCH, pre-release tags",
            "Conventional Commits and Commitizen for automated changelogs",
            "Pull Request workflows: PR templates, draft PRs, required reviewers, CODEOWNERS",
            "Branch protection rules: status checks, linear history, signed commits",
            "GitHub Actions: events, jobs, steps, runners, matrix builds, workflow_dispatch",
            "GitHub Actions: secrets, environments, OIDC for keyless Azure auth",
            "Reusable workflows (workflow_call) and composite actions",
            "GitHub Advanced Security: Dependabot, secret scanning, code scanning (CodeQL)",
            "Monorepo vs polyrepo: path filters, turbo repo, workspace management",
            "Git hooks: pre-commit, pre-push hooks for local enforcement",
          ],
          tools: ["Git", "GitHub", "GitHub Actions", "CodeQL", "Dependabot", "Commitizen"],
          lab: "Implement enterprise Git workflow for a 5-developer team: branch policies, PR templates, CODEOWNERS, GitHub Actions CI with CodeQL scan and Dependabot weekly updates",
          labOutcome: "Protected main branch — no direct pushes, all code reviewed and security-scanned before merge",
        },
        {
          title: "Azure DevOps Platform: Boards, Repos, Artifacts & Pipelines",
          week: "Week 10",
          topics: [
            "Azure Boards: Epics → Features → User Stories → Tasks → Bugs hierarchy",
            "Sprint planning, velocity tracking, burndown charts",
            "Queries, dashboards and team views",
            "Azure Repos: Git hosting, branch policies, protected branches",
            "Azure Repos vs GitHub: when to use which in enterprise",
            "Azure Artifacts: npm, NuGet, Maven, Python (PyPI) and Universal Packages",
            "Upstream sources: proxy public registries through private feed",
            "Artifact views: Release, Prerelease, Local",
            "Self-hosted agents: Docker agent, scale set agents (VMSS-backed)",
            "Pipeline agents: capabilities, demands and agent pools",
            "Service connections: Azure Resource Manager (workload identity, service principal, managed identity)",
            "Variable groups, library secrets and Azure Key Vault-backed variable groups",
          ],
          tools: ["Azure DevOps", "Azure Boards", "Azure Artifacts", "Azure Repos"],
          lab: "Set up a complete Azure DevOps project: 3-sprint board, Git repo with branch policies, npm package published to Artifacts feed, and a Key Vault-backed variable group for secrets",
          labOutcome: "Enterprise DevOps project with auditable sprint history and zero secrets in pipeline YAML",
        },
        {
          title: "CI/CD Pipeline Engineering: YAML Multi-Stage Pipelines",
          week: "Week 11",
          topics: [
            "YAML pipeline syntax deep dive: trigger, pr, stages, jobs, steps, resources",
            "Stage dependencies: dependsOn, conditions (succeeded, failed, always, custom)",
            "Job strategies: parallel, sequential, matrix (cross-platform builds)",
            "Deployment jobs: runOnce, rolling, canary strategies",
            "Environments: approval gates, branch filters, exclusions",
            "Deployment strategies: Rolling (maxParallel), Blue-Green, Canary (% traffic)",
            "Pipeline templates: step templates, job templates, stage templates, extends",
            "Runtime parameters and conditional template insertion",
            "Pipeline caching: @azure/pipelines-cache, npm, Maven, pip, Docker layer cache",
            "Artifact publishing and downloading across stages",
            "Deployment gate types: Query Azure Monitor alert, Invoke REST API, Manual approval",
            "Release pipeline analytics: pass rate, duration, failure trends",
          ],
          tools: ["Azure Pipelines", "YAML", "Azure Environments", "GitHub Actions"],
          lab: "Build a 5-stage pipeline: Build → Unit Test → Docker Build & Push to ACR → Deploy to AKS Staging (auto) → Deploy to AKS Production (manual approval gate) with Azure Monitor deployment gate",
          labOutcome: "Production deployment requires 2-step approval and Azure Monitor health gate — zero failed deployments reach prod without sign-off",
        },
        {
          title: "Docker & Containerisation for DevOps",
          week: "Week 12",
          topics: [
            "Container architecture: namespaces (PID, NET, MNT, UTS, IPC), cgroups, overlay filesystem",
            "Dockerfile: FROM, RUN (exec vs shell form), COPY vs ADD, ARG vs ENV, EXPOSE, ENTRYPOINT vs CMD",
            "Multi-stage builds: builder stage → runtime stage, distroless base images",
            "Image layers, caching strategy and .dockerignore optimisation",
            "Docker BuildKit: parallel stages, cache mounts, secret mounts",
            "Docker networks: bridge, host, overlay, macvlan, none",
            "Docker volumes: named volumes vs bind mounts vs tmpfs",
            "Docker Compose: services, networks, volumes, profiles, depends_on with condition",
            "Azure Container Registry (ACR): push/pull, geo-replication, webhooks, content trust",
            "Container image vulnerability scanning: Trivy, Grype, Microsoft Defender for Containers",
            "Distroless and scratch images: minimal attack surface",
            "Container runtime security: non-root user, read-only filesystem, no-new-privileges, seccomp profiles",
          ],
          tools: ["Docker", "Docker Compose", "ACR", "Trivy", "Docker Scout", "BuildKit"],
          lab: "Containerise a Node.js + PostgreSQL + Redis application: multi-stage Dockerfile (160MB → 38MB), Compose for dev, Trivy scan (zero critical CVEs), push to ACR via CI pipeline",
          labOutcome: "Production-ready container: signed, scanned, minimal (38MB), no root, pushed to private registry via automated pipeline",
        },
        {
          title: "Kubernetes & Azure Kubernetes Service (AKS)",
          week: "Week 13–14",
          topics: [
            "Kubernetes architecture: kube-apiserver, etcd, kube-scheduler, kube-controller-manager, cloud-controller-manager",
            "Node components: kubelet, kube-proxy, container runtime (containerd)",
            "Pods: single-container, multi-container (sidecar, ambassador, adapter), init containers",
            "Deployments: rolling update strategy, maxSurge, maxUnavailable, rollback",
            "StatefulSets: stable network identity, ordered deployment, PVC templates",
            "DaemonSets: node monitoring agents, log shippers",
            "Services: ClusterIP, NodePort, LoadBalancer, ExternalName, Headless",
            "Ingress: NGINX Ingress Controller, path-based and host-based routing",
            "TLS termination: cert-manager + Let's Encrypt (ClusterIssuer, Certificate)",
            "ConfigMaps and Secrets: env vars, volume mounts, ExternalSecrets Operator",
            "Persistent Volumes: dynamic provisioning, StorageClass, Azure Disk, Azure Files",
            "Horizontal Pod Autoscaler (HPA): CPU/memory, custom metrics via KEDA",
            "AKS: managed control plane, node pools (system + user), cluster autoscaler",
            "AKS networking: kubenet vs CNI (Azure CNI, Cilium CNI)",
            "AKS Workload Identity: pod-level Entra ID identity (replaces AAD Pod Identity)",
            "Kubernetes RBAC: Role, ClusterRole, RoleBinding, ClusterRoleBinding",
            "Network Policies: ingress/egress rules, Calico vs Azure NPM",
            "Helm: charts, values.yaml, templates, hooks, chart museum, OCI registry",
            "Helm: umbrella charts, chart dependencies, helmfile for multi-release management",
            "Argo CD: GitOps sync, Application CRDs, App of Apps pattern",
            "Kubernetes troubleshooting: kubectl describe, logs, exec, events, resource quotas",
          ],
          tools: ["Kubernetes", "AKS", "Helm", "cert-manager", "Argo CD", "KEDA", "kubectl"],
          lab: "Deploy a production-grade microservices app (API + worker + frontend) on AKS: Helm chart per service, Ingress with TLS, HPA with custom metrics via KEDA, Argo CD for GitOps sync, Workload Identity for Key Vault access",
          labOutcome: "GitOps-managed AKS cluster: any git push to main auto-deploys within 90 seconds, zero manual kubectl apply",
        },
        {
          title: "Infrastructure as Code: Terraform on Azure",
          week: "Week 15",
          topics: [
            "Terraform / OpenTofu 1.12.0 (May 2026): providers, state (local, remote), plan, apply, destroy",
            "HCL syntax: resource, data source, variable, output, local, module blocks",
            "AzureRM provider: authentication (service principal, managed identity, OIDC)",
            "Resource targeting: -target, -replace, state manipulation (mv, rm, import)",
            "Terraform state: remote backend (Azure Storage), state locking (Blob lease)",
            "Modules: input variables, output values, module composition, version constraints",
            "Terraform Registry: public modules (Azure/network, Azure/aks, Azure/vm)",
            "Dynamic blocks, for_each, count, conditional expressions",
            "Terraform testing: terraform validate, fmt, plan -detailed-exitcode, terratest",
            "Terraform in CI/CD: plan on PR comment (Atlantis/Terraform Cloud), apply on merge",
            "Bicep: comparison with Terraform, when to use which in Azure-only shops",
            "State drift: terraform refresh, detecting and remediating configuration drift",
          ],
          tools: ["Terraform", "AzureRM Provider", "Terraform Cloud", "Atlantis", "Bicep"],
          lab: "Terraform-provision a complete AKS environment: VNet, AKS cluster, ACR, Key Vault, Log Analytics — remote state in Azure Storage, CI/CD plan on PR (with plan output as PR comment), apply on merge to main",
          labOutcome: "100% infrastructure-as-code: no manual Azure Portal clicks, full audit trail via Git history",
        },
        {
          title: "Monitoring, Observability & SRE Fundamentals",
          week: "Week 16",
          topics: [
            "Prometheus: scrape model, metrics types (Counter, Gauge, Histogram, Summary), relabelling",
            "PromQL: rate(), irate(), histogram_quantile(), topk(), label_replace()",
            "Prometheus Operator: ServiceMonitor, PodMonitor, PrometheusRule CRDs",
            "Grafana: data sources, panel types, variables, annotations, alerting",
            "Grafana Loki: log aggregation, LogQL, label-based indexing",
            "Grafana Tempo: distributed tracing, TraceQL",
            "OpenTelemetry: instrumentation libraries, OTEL Collector, exporters",
            "Azure Monitor: Container Insights for AKS, Managed Prometheus, Managed Grafana",
            "Log Analytics: Container Insights KQL queries, AKS diagnostic logs",
            "SRE principles: toil definition, error budget concept, reliability targets",
            "SLIs: request latency p50/p95/p99, error rate, saturation, traffic",
            "SLOs: defining targets, burn rate alerts, multi-window multi-burn-rate",
            "Incident Management: severity levels, on-call rotations, blameless postmortems",
            "Chaos Engineering: Azure Fault Injection Simulator, LitmusChaos on AKS",
          ],
          tools: ["Prometheus", "Grafana", "Loki", "OpenTelemetry", "Azure Monitor", "Container Insights"],
          lab: "Deploy the kube-prometheus-stack via Helm: 30+ Grafana dashboards (cluster, namespace, pod, API latency), Loki for log aggregation, SLO dashboard with burn rate alerts for a production service",
          labOutcome: "Operational visibility dashboard: p99 latency, error budget burn rate, and auto-alerting when budget burns 5× faster than expected",
        },
        {
          title: "AZ-400 Exam Preparation & Capstone",
          week: "Week 17",
          topics: [
            "AZ-400 exam (updated April 24, 2026): 40–60 questions, performance-based tasks",
            "Exam domains: Source control (10–15%), CI/CD (40–45%), Security (10–15%), Monitoring (10–15%), Compliance (5–10%)",
            "Common scenario questions: merge strategy selection, release gate configuration, service connection permissions",
            "3 full mock exams with detailed answer explanations",
            "AZ-400 hands-on scenarios from real exam bank",
          ],
          tools: ["Microsoft Learn", "AZ-400 Practice Tests", "MeasureUp"],
          lab: "Complete 3 timed mock exams (target: 750/1000+) and review all wrong answers with mentor guidance",
          labOutcome: "AZ-400 exam-ready with 80%+ mock exam score across all domains",
        },
      ],
      capstone: {
        title: "Phase 2 Capstone — Production DevOps Platform",
        deliverables: [
          "GitHub repo: branch protection, CODEOWNERS, CodeQL security scanning",
          "5-stage Azure Pipeline: Build → Test → Docker→ACR → Staging (auto) → Prod (approval gate)",
          "Multi-service AKS deployment: Helm charts, Ingress, TLS, Argo CD GitOps",
          "Terraform IaC: VNet + AKS + ACR + Key Vault, remote state, CI/CD plan/apply",
          "kube-prometheus-stack: 30 dashboards, SLO burn rate alerts, Loki log aggregation",
          "Zero-downtime deployment: blue-green switchover with automated smoke test gate",
        ],
      },
    },

    /* ═══════════════════════════════════════════════════════════
       PHASE 3 — AI-Powered DevSecOps (8 Weeks)
    ═══════════════════════════════════════════════════════════ */
    {
      label: "Phase 3",
      title: "AI-Powered DevSecOps Engineering",
      duration: "8 Weeks",
      cert: "AI DevSecOps + GitHub Copilot",
      color: "bg-[#FFF7ED] text-[#9A3412] border-[#FED7AA]",
      icon: Bot,
      objective:
        "Learn how AI is reshaping cloud operations, security and platform engineering. You will use GitHub Copilot to generate infrastructure code, build AIOps monitoring platforms, secure pipelines with DevSecOps tooling, and operate a Security Operations Centre using Microsoft Sentinel — skills that less than 5% of cloud engineers currently have.",
      modules: [
        {
          title: "DevSecOps Fundamentals & Shift-Left Security",
          week: "Week 18",
          topics: [
            "DevSecOps philosophy: security as a first-class pipeline citizen, not a gate",
            "Shift-Left security: find defects at commit time, not production",
            "OWASP Top 10 (2021): Injection, Broken Auth, IDOR, Security Misconfiguration, SSRF etc.",
            "SAST (Static Analysis): Semgrep, SonarQube, CodeQL — rule writing and custom patterns",
            "DAST (Dynamic Analysis): OWASP ZAP, Nuclei — baseline scan vs full scan",
            "SCA (Software Composition Analysis): Dependency-Check, Snyk, FOSSA — license risk and CVE detection",
            "Container scanning: Trivy (image, filesystem, repo, SBOM), Grype, Microsoft Defender for Containers",
            "Secret detection: GitLeaks, TruffleHog, GitHub Secret Scanning — pre-commit and CI gates",
            "SBOM (Software Bill of Materials): CycloneDX and SPDX formats, Syft generation",
            "Policy as Code: Open Policy Agent (OPA), Rego language, Conftest for Terraform/K8s",
            "Admission controllers: Gatekeeper (OPA), Kyverno — enforce policies at cluster level",
            "DevSecOps Maturity Model (DSOMM): assess and plan your organisation's security journey",
          ],
          tools: ["Semgrep", "Trivy", "OWASP ZAP", "GitLeaks", "OPA/Rego", "Kyverno", "Snyk"],
          lab: "Add full security pipeline to an existing CI/CD: SAST (Semgrep) + container scan (Trivy, zero critical allowed) + DAST (ZAP baseline) + secret detection (GitLeaks) + OPA policy validation on Terraform plan",
          labOutcome: "Security pipeline blocks every critical CVE, exposed secret and misconfigured Terraform resource before it reaches any environment",
        },
        {
          title: "GitHub Copilot for DevOps & Infrastructure Engineering",
          week: "Week 19",
          topics: [
            "GitHub Copilot architecture: Codex model, context window, prompt construction",
            "Copilot in VS Code: inline suggestions, Copilot Chat, /explain, /fix, /tests commands",
            "Copilot for infrastructure: generating Terraform resources, modules and variable files",
            "Copilot for Kubernetes: Helm chart templates, Deployment YAML, HPA configs",
            "Copilot for pipelines: GitHub Actions workflows, Azure Pipeline YAML, Jenkinsfile",
            "Copilot for scripts: Bash automation, PowerShell, Python boto3/azure-sdk",
            "Copilot for security: explaining CVEs, suggesting remediations, writing OPA rules",
            "Copilot CLI: gh copilot explain and gh copilot suggest for terminal commands",
            "Prompt engineering for DevOps: context priming, role prompting, chain-of-thought for complex IaC",
            "Evaluating Copilot output: hallucination risks, deprecated API detection, security review",
            "GitHub Copilot Enterprise: knowledge bases, repository indexing, org-level policies",
          ],
          tools: ["GitHub Copilot", "VS Code", "Copilot Chat", "Copilot CLI", "GitHub Copilot Enterprise"],
          lab: "Use Copilot to generate a complete Terraform module (AKS + ACR + Key Vault), a 4-stage GitHub Actions pipeline, and a Kubernetes Helm chart — review, test and deploy all generated code",
          labOutcome: "3× faster infrastructure delivery: 45-minute task (write Terraform module from scratch) completed in 14 minutes with Copilot",
        },
        {
          title: "AI-Powered Infrastructure Automation & ChatOps",
          week: "Week 20",
          topics: [
            "Azure AI Studio: model deployment, prompt flow, evaluation pipelines",
            "Azure OpenAI Service: GPT-4 for infrastructure Q&A, documentation generation",
            "AI for Terraform: natural language → Terraform plan using GPT-4 function calling",
            "AI for ARM/Bicep: generate and explain templates from architecture descriptions",
            "Infrastructure optimisation: Azure Advisor + AI recommendations (cost, security, reliability)",
            "AI-powered code review: PR descriptions, change impact analysis, risk scoring",
            "ChatOps integration: Azure DevOps + Microsoft Teams bot for pipeline status and approval",
            "ChatOps with Slack: Slack bot triggering Azure Pipeline via incoming webhooks",
            "Auto-remediation: Azure Automation runbooks triggered by Azure Monitor alerts",
            "Logic Apps for automated responses: resize VM on high CPU, scale AKS node pool",
            "AI incident triage: GPT-4 summarising Log Analytics alerts into plain-English incident tickets",
          ],
          tools: ["Azure OpenAI", "Azure AI Studio", "Azure Automation", "Logic Apps", "Microsoft Teams", "Slack"],
          lab: "Build an AI-powered infra assistant: natural language → Terraform plan → CI/CD deployment, plus a Teams bot that shows pipeline status, approves deployments and summarises Azure Monitor alerts in plain English",
          labOutcome: "End-to-end AI-assisted deployment: describe infrastructure in English, deploy to Azure in under 10 minutes",
        },
        {
          title: "Cloud Security Automation: Defender for Cloud & Key Vault",
          week: "Week 21",
          topics: [
            "Microsoft Defender for Cloud: Secure Score, regulatory compliance (ISO 27001, PCI DSS, NIST)",
            "Defender plans: Defender for Servers (P1/P2), Containers, Databases, App Service, Key Vault, Storage",
            "Security recommendations: severity levels, quick fixes, exemptions",
            "Just-In-Time (JIT) VM access: approved IP ranges, time-limited access",
            "Adaptive application controls: allowlist machine learning recommendations",
            "Azure Key Vault: secrets, keys (RSA, EC, AES), certificates lifecycle management",
            "Key Vault access: RBAC vs access policies — Microsoft's recommended RBAC model",
            "Managed Identity + Key Vault in pipelines: zero hardcoded credentials, ever",
            "GitHub Advanced Security: secret scanning patterns, push protection, dependency review",
            "Azure Policy security baselines: CIS Benchmark v2.0, Azure Security Benchmark",
            "Container security: Pod Security Standards (Restricted/Baseline/Privileged), seccomp, AppArmor",
            "Microsoft Defender for Containers: runtime threat detection, Kubernetes audit log analysis",
          ],
          tools: ["Defender for Cloud", "Azure Key Vault", "GitHub Advanced Security", "Azure Policy", "Managed Identity"],
          lab: "Security hardening sprint: improve Defender Secure Score from 45% → 90%+, implement Key Vault in all pipelines via Managed Identity, enable Pod Security Standards on AKS, and fix all Critical/High Defender recommendations",
          labOutcome: "Enterprise-grade security posture: 90%+ Secure Score, zero pipeline secrets in plaintext, all containers running as non-root with read-only filesystem",
        },
        {
          title: "AIOps: Intelligent Monitoring & Self-Healing Infrastructure",
          week: "Week 22",
          topics: [
            "AIOps definition: ML-driven event correlation, anomaly detection and root cause analysis",
            "Azure Monitor dynamic thresholds: ML-based anomaly detection for metrics",
            "Azure Monitor AI insights: smart groups to correlate related alerts",
            "Container Insights: live node/pod metrics, recommended alerts, GPU node monitoring",
            "Log-based anomaly detection: KQL time-series analysis functions (series_decompose_anomalies)",
            "Predictive scaling: KEDA with Azure Monitor metrics, custom metric autoscaling",
            "Self-healing patterns: CrashLoopBackOff auto-restart analysis, pod disruption budgets",
            "Azure Automation: PowerShell/Python runbooks, schedules, webhooks, hybrid workers",
            "Auto-remediation runbooks: restart failed services, scale resources, rotate secrets",
            "Datadog (overview): integration with Azure, APM, log management, AI-powered alerts",
            "New Relic (overview): AI observability, change tracking, error tracking",
            "SRE automation: toil metrics, automation targets, error budget policies",
          ],
          tools: ["Azure Monitor", "Azure Automation", "KEDA", "Container Insights", "Prometheus Operator"],
          lab: "Build an intelligent monitoring + auto-remediation platform: anomaly-detection alert → Logic App trigger → auto-scale AKS node pool, plus an Automation runbook that restarts a crashed deployment and creates a DevOps work item",
          labOutcome: "Self-healing cluster: CPU spike → KEDA scales pods within 30 seconds → if pods fail, runbook restarts deployment → ticket auto-created in Azure Boards",
        },
        {
          title: "Microsoft Sentinel: SIEM, Threat Hunting & SOAR",
          week: "Week 23",
          topics: [
            "SIEM fundamentals: log ingestion, normalisation, correlation and alerting",
            "Microsoft Sentinel architecture: workspaces, data connectors, tables, retention",
            "Data connectors: Azure Activity, Microsoft Defender XDR, Office 365, AWS (S3 via EventHub), custom CEF/Syslog",
            "Common Information Model (CIM): normalised table schemas (SecurityEvent, Syslog, AzureActivity, SigninLogs)",
            "KQL for security: SecurityEvent | where EventID == 4625 — failed logins, lateral movement patterns",
            "Scheduled analytics rules: KQL query + entity mapping + alert trigger",
            "ML-based analytics rules: Fusion (multi-stage attack detection), UEBA anomalies",
            "MITRE ATT&CK framework: tactics, techniques, sub-techniques — 14 tactics mapped to Sentinel rules",
            "Workbooks: SecurityInsights workbook templates, custom SOC dashboards",
            "Threat hunting: bookmarks, hunting queries, Jupyter notebooks integration",
            "Incidents: severity, status, comments, assignment, investigation graph",
            "SOAR with Logic Apps: automated playbooks — block IP in Firewall, disable compromised account, notify SOC team",
            "Microsoft Security Copilot integration with Sentinel (preview): AI-powered threat summarisation",
          ],
          tools: ["Microsoft Sentinel", "KQL", "Logic Apps (SOAR)", "MITRE ATT&CK", "Defender XDR"],
          lab: "Build a Security Operations Centre: connect 5 data sources, write 10 custom KQL detection rules (brute force, privilege escalation, exfiltration), create MITRE ATT&CK coverage heatmap, and automate incident response (block IP + disable account + Teams notification) via Logic App playbook",
          labOutcome: "Operational SOC: detects brute force attack within 5 minutes, automatically blocks attacker IP and notifies security team — zero manual intervention",
        },
        {
          title: "Career Preparation, Mock Interviews & Final Capstone",
          week: "Week 24",
          topics: [
            "ATS-optimised resume: cloud/DevOps keyword strategy, quantified achievements",
            "GitHub portfolio: README structure, project showcasing, contribution graph",
            "LinkedIn optimisation: headline formula, featured section, recruiter visibility",
            "Technical interview preparation: 100+ DevOps/cloud interview Q&A",
            "System design for DevOps: design a CI/CD platform for 100 engineers",
            "Kubernetes troubleshooting scenarios: OOMKilled, ImagePullBackOff, CrashLoopBackOff",
            "Azure architecture whiteboard questions: design an e-commerce platform for 1M users",
            "Behavioural interviews: STAR format, incident stories, mentorship examples",
            "Salary negotiation: market rates by role and city, counter-offer strategies",
            "Offer evaluation: base, RSU, bonus, ESOP — total compensation comparison",
          ],
          tools: ["LinkedIn", "GitHub", "LeetCode", "Excalidraw"],
          lab: "Complete 3 mock technical interviews (recorded), refine resume with mentor feedback, and submit GitHub portfolio with 6 production-grade projects for peer review",
          labOutcome: "Job-ready: polished resume, 6-project portfolio, 3 mock interview sessions with written feedback",
        },
      ],
      capstone: {
        title: "Phase 3 Final Capstone — Intelligent Enterprise Platform",
        deliverables: [
          "Secure Azure infrastructure: Terraform-provisioned, Defender for Cloud 90%+ Secure Score",
          "Full DevSecOps pipeline: SAST + SCA + Trivy + DAST + OPA gates, zero critical CVEs in prod",
          "AKS with Pod Security Standards, Workload Identity, Gatekeeper admission policies",
          "GitHub Copilot-generated and reviewed Terraform modules + Helm charts",
          "Microsoft Sentinel SOC: 10 custom KQL rules, MITRE ATT&CK heatmap, auto-remediation playbook",
          "AIOps platform: anomaly detection + KEDA autoscaling + self-healing runbooks",
          "GitHub portfolio repository with full README, architecture diagram and demo video",
        ],
      },
    },
  ],

  bonusTracks: [
    {
      icon: Terminal,
      title: "Linux for DevOps Engineers",
      topics: [
        "Ubuntu/RHEL: process management, systemd, journalctl",
        "File permissions, ACLs, sudo and PAM",
        "Bash scripting: loops, functions, error handling, traps",
        "Text processing: grep, sed, awk, cut, sort, uniq",
        "Network tools: netstat, ss, tcpdump, curl, nmap",
        "Package management: apt, dnf, snap, compiling from source",
      ],
    },
    {
      icon: Code2,
      title: "Python for DevOps Automation",
      topics: [
        "azure-sdk-for-python: compute, storage, network management",
        "Paramiko: SSH automation across VM fleets",
        "Requests: Azure REST API and webhook automation",
        "PyYAML: parsing and generating Kubernetes manifests",
        "Pytest: testing infrastructure code and Ansible roles",
        "Click: building CLI tools for internal DevOps workflows",
      ],
    },
    {
      icon: Bot,
      title: "AI Prompt Engineering for Engineers",
      topics: [
        "Prompt patterns: chain-of-thought, tree-of-thought, ReAct",
        "GitHub Copilot mastery: context priming, multi-file context",
        "Azure OpenAI: GPT-4 API, function calling, JSON mode",
        "Building AI-powered runbooks and incident summaries",
        "AI code review automation: PR description generation",
        "Evaluating AI output: hallucination detection, security review",
      ],
    },
  ],

  certifications: [
    { code: "AZ-104",    title: "Microsoft Azure Administrator Associate",   emoji: "🔧" },
    { code: "AZ-400",    title: "Microsoft DevOps Engineer Expert",           emoji: "⚙️" },
    { code: "GitHub Copilot", title: "GitHub Copilot Fundamentals",          emoji: "🤖" },
    { code: "SC-900",    title: "Microsoft Security Fundamentals (optional)", emoji: "🛡️" },
    { code: "CKA Prep",  title: "Certified Kubernetes Administrator (prep)",  emoji: "☸️" },
  ],

  projects: [
    { title: "Enterprise Azure Landing Zone",            desc: "Hub-spoke VNet, Azure Firewall, Bastion, Management Groups, Azure Policy, Entra ID PIM — full enterprise baseline" },
    { title: "Auto-Scaling VMSS Web Tier",               desc: "VMSS with custom CPU/HTTP scaling rules, Application Gateway WAF, Recovery Services backup, and Azure Monitor alerts" },
    { title: "Secure Data Platform",                     desc: "Blob lifecycle management (hot→archive→delete), Azure Files with File Sync, CMK encryption via Key Vault, WORM immutability" },
    { title: "Blue-Green App Service Deployment",        desc: "Python Flask app with staging slot, GitHub Actions CI/CD, slot swap with traffic splitting, Application Insights monitoring" },
    { title: "Enterprise CI/CD Pipeline (5-stage)",      desc: "Build → SAST → Docker+ACR → AKS Staging (auto) → AKS Prod (approval + Azure Monitor gate) — zero manual steps after commit" },
    { title: "Production AKS Platform",                  desc: "Multi-service app: Helm charts, NGINX Ingress, TLS via cert-manager, HPA with KEDA, Argo CD GitOps, Workload Identity for Key Vault" },
    { title: "Terraform IaC Azure Stack",                desc: "Modular Terraform: VNet + AKS + ACR + Key Vault + Log Analytics, remote state, CI plan on PR with comment output, apply on merge" },
    { title: "DevSecOps Security Pipeline",              desc: "Full security pipeline: Semgrep SAST + Trivy container scan + ZAP DAST + GitLeaks + OPA Conftest — blocks every critical issue" },
    { title: "kube-prometheus-stack Observability",      desc: "Prometheus Operator + Grafana (30 dashboards) + Loki log aggregation + SLO burn rate multi-window alerts for production services" },
    { title: "Copilot-Generated Infrastructure",         desc: "Use GitHub Copilot to generate, review and deploy a Terraform AKS module, GitHub Actions pipeline, and Helm chart — 3× faster delivery" },
    { title: "Microsoft Sentinel SOC",                   desc: "10 KQL detection rules, MITRE ATT&CK heatmap, automated playbook (block IP + disable account + Teams alert) — operational SOC in one day" },
    { title: "AIOps Self-Healing Platform",              desc: "Azure Monitor anomaly detection → Logic App → auto-scale AKS / restart pods → Automation runbook creates Azure Boards ticket automatically" },
    { title: "AI Infrastructure Assistant",              desc: "GPT-4 natural language → Terraform plan → CI/CD deploy pipeline + Teams bot for pipeline status, approval and alert summarisation" },
    { title: "Zero-Trust Security Hardening",            desc: "Defender for Cloud 90%+ Secure Score, Pod Security Standards on AKS, Gatekeeper policies, Managed Identity everywhere — zero plaintext secrets" },
    { title: "Final Portfolio Capstone",                 desc: "All 3 phases integrated: Terraform infra → CI/CD pipeline → AKS → DevSecOps gates → Sentinel SOC → AIOps monitoring — full GitHub portfolio" },
  ],

  technologies: [
    "Azure VMs", "AKS", "ACR", "Azure App Service", "Azure Functions",
    "Entra ID", "Key Vault", "Azure Monitor", "Log Analytics (KQL)", "Application Insights",
    "Terraform / OpenTofu 1.12", "Bicep", "Azure DevOps", "GitHub Actions", "Argo CD v3.3",
    "Docker v29.3", "Kubernetes 1.36.1", "Helm", "cert-manager", "KEDA",
    "Prometheus", "Grafana", "Loki", "OpenTelemetry", "Microsoft Sentinel",
    "GitHub Copilot", "Claude Code", "Azure OpenAI (GPT-5.5)", "Trivy", "Semgrep", "OPA/Rego",
    "Gatekeeper", "Logic Apps", "Azure Automation", "Defender for Cloud", "Linux/Bash",
  ],

  careerTiers: [
    {
      level: "Entry-Level (0–1 yr) · ₹4–7 LPA",
      roles: ["Azure Cloud Administrator", "Cloud Support Engineer", "Azure Operations Engineer", "Junior DevOps Engineer"],
      color: "border-[#BFDBFE] bg-[#EFF6FF]",
    },
    {
      level: "Mid-Level (1–3 yr) · ₹8–16 LPA",
      roles: ["DevOps Engineer", "Azure DevOps Engineer", "Platform Engineer", "Cloud Security Engineer"],
      color: "border-[#BBF7D0] bg-[#F0FDF4]",
    },
    {
      level: "Advanced (3+ yr) · ₹18–35 LPA",
      roles: ["DevSecOps Engineer", "Site Reliability Engineer (SRE)", "AI Operations Engineer", "Cloud Architect"],
      color: "border-[#FED7AA] bg-[#FFF7ED]",
    },
  ],

  idealFor: [
    {
      icon: GraduationCap,
      title: "Students & Final-Year B.Tech",
      desc: "Get AZ-104 + AZ-400 certifications and 15 real projects before graduation. MNCs like TCS, Infosys, Wipro and mid-size cloud companies specifically hire for these exact skills.",
      color: "text-[#4F46E5]",
      bg: "bg-[#EEF2FF]",
    },
    {
      icon: Briefcase,
      title: "Freshers & Junior IT Engineers",
      desc: "Structured 6-month path from zero to job-ready. You will have more practical experience than most 2-year IT professionals by the time you complete this program.",
      color: "text-[#059669]",
      bg: "bg-[#ECFDF5]",
    },
    {
      icon: Users2,
      title: "Working Professionals",
      desc: "Transition from sysadmin, software dev or IT support into Cloud, DevOps or Platform Engineering. Weekend batches available — designed around your work schedule.",
      color: "text-[#D97706]",
      bg: "bg-[#FFFBEB]",
    },
  ],

  faqs: [
    {
      q: "Do I need any prior cloud or DevOps experience to join?",
      a: "No. Phase 1 starts from absolute cloud fundamentals. A basic understanding of Windows/Linux and some exposure to programming concepts (any language) is helpful but not required. We cover Linux and Python in the bonus tracks.",
    },
    {
      q: "What is the time commitment per week?",
      a: "Plan for 15–20 hours per week: 3–4 hours of live sessions (weekday evenings or weekends), 3–4 hours of self-paced LMS content, and 6–8 hours of hands-on lab work. If you can dedicate more time, you can complete labs faster and go deeper.",
    },
    {
      q: "Are the AZ-104 and AZ-400 exam vouchers included?",
      a: "Exam voucher fees are not included in the program fee. However, we provide a structured exam preparation schedule, 3 full-length mock exams per certification, and guidance on the Microsoft Exam Replay offer (free retake if you fail). Many learners pass on the first attempt.",
    },
    {
      q: "What kind of support is available after the program?",
      a: "Lifetime LMS access, alumni WhatsApp community, monthly Q&A sessions, resume reviews and mock interview sessions. Placement support includes referrals to our hiring partner companies for active job seekers.",
    },
    {
      q: "Is this program available in online-only or in-person mode?",
      a: "The program is fully online: live instructor-led sessions via Microsoft Teams/Zoom, labs on Azure (using your own free or paid account), and LMS for recorded sessions and resources. In-person workshops are held occasionally in Lucknow for local students.",
    },
    {
      q: "What Azure costs will I incur during the program?",
      a: "Most labs are designed to run on the Azure Free Tier ($200 credit for 30 days). For extended labs (AKS, Sentinel, Defender), we estimate ₹1,500–2,500 in Azure costs spread across 6 months. We teach cost-optimisation techniques in Phase 1 so you always know what you're spending.",
    },
    {
      q: "How is this different from Microsoft Learn or Udemy courses?",
      a: "Microsoft Learn and Udemy are self-paced with no mentorship, no real projects and no accountability. This program gives you live mentor sessions, industry-grade projects that go on your GitHub and resume, doubt-clearing sessions, mock interviews and placement support — everything that actually gets you a job.",
    },
    {
      q: "What is the refund policy?",
      a: "Full refund within 7 days of enrollment if you have attended fewer than 2 live sessions. After that, a partial refund is available on a pro-rata basis. Contact admissions at genznextofficial@gmail.com for details.",
    },
  ],
};

export default function MicrosoftCloudAiDevOpsMasterPage() {
  return <ProgramPageLayout data={data} />;
}
