import {
  BadgeCheck,
  Bot,
  BrainCircuit,
  BriefcaseBusiness,
  Building2,
  Cloud,
  CloudCog,
  Cpu,
  Code2,
  DatabaseZap,
  GitBranch,
  GraduationCap,
  Handshake,
  Layers3,
  LifeBuoy,
  MessageSquareText,
  MonitorSmartphone,
  ShieldCheck,
  Sparkles,
  Users,
  Workflow,
} from "lucide-react";

export const iconMap = {
  ai: Bot,
  awards: BadgeCheck,
  brain: BrainCircuit,
  briefcase: BriefcaseBusiness,
  building: Building2,
  cloud: Cloud,
  cloudCog: CloudCog,
  code: Code2,
  community: Users,
  cpu: Cpu,
  database: DatabaseZap,
  graduation: GraduationCap,
  gitBranch: GitBranch,
  guidance: Handshake,
  layers: Layers3,
  message: MessageSquareText,
  support: LifeBuoy,
  devices: MonitorSmartphone,
  shield: ShieldCheck,
  sparkles: Sparkles,
  topology: Workflow,
} as const;

export type IconKey = keyof typeof iconMap;
