import { Bot, Briefcase, Clock3, Code2, Cpu, FolderKanban, GraduationCap, Layers, Sparkles, Terminal, Users2 } from "lucide-react";
import { ProgramPageLayout, type ProgramPageData } from "@/components/programs/program-page-layout";
import { buildMetadata } from "@/lib/metadata";

export const metadata = buildMetadata({
  title: "Master AI & Generative AI Program | GenZNext Research & Training",
  description: "20-week AI engineering program: Python for AI, Prompt Engineering, LangChain, Generative AI, RAG Systems, AI Agents & cloud deployment. 12+ real projects, live mentorship.",
  path: "/programs/ai-generative-ai-master",
});

const data: ProgramPageData = {
  badge: "AI & Generative AI Track",
  badgeColor: "border-[#C7D2FE] bg-[#EEF2FF] text-[#4338CA]",
  tagline: "Become a Job-Ready AI Engineer",
  title: "Master AI & Generative AI Program",
  description:
    "A 20-week, mentor-led AI engineering program that takes you from Python basics to building production-grade GenAI applications, RAG pipelines and autonomous AI agents. No prior AI experience needed — just curiosity and commitment.",
  chips: ["Live Instructor-Led", "Python for AI", "LangChain & LlamaIndex", "RAG & Vector DBs", "AI Agents", "LMS Access", "Placement Support"],
  stats: [
    { icon: Clock3,       label: "20 Weeks" },
    { icon: Layers,       label: "4 Phases" },
    { icon: FolderKanban, label: "12+ Projects" },
    { icon: Users2,       label: "Live Mentorship" },
  ],
  price:         "Rs. 24,999",
  originalPrice: "Rs. 54,999",
  priceLabel:    "54% off — All 4 phases + bonus tracks",
  enrollSlug:    "ai-generative-ai-master-program",
  enrollFeatures: [
    { icon: Clock3,       text: "20 Weeks (5 Months)" },
    { icon: GraduationCap,text: "Beginner to Advanced" },
    { icon: FolderKanban, text: "12+ Real-World AI Projects" },
    { icon: Cpu,          text: "OpenAI, LangChain, LlamaIndex" },
    { icon: Sparkles,     text: "RAG + AI Agents included" },
    { icon: Users2,       text: "Live Sessions + LMS Access for Life" },
  ],
  roadmap: ["Python & AI Foundations", "Prompt Engineering & LLMs", "Generative AI & RAG", "AI Agents & Deployment"],

  phases: [
    {
      label: "Phase 1",
      title: "Python & AI Foundations",
      duration: "4 Weeks",
      color: "bg-[#EEF2FF] text-[#4338CA] border-[#C7D2FE]",
      icon: Code2,
      objective:
        "Build the Python and data science foundations required for AI engineering. Learn how to work with data, train basic ML models, and understand how AI pipelines are structured before touching LLMs.",
      modules: [
        {
          title: "Python for AI Engineering",
          week: "Week 1",
          topics: [
            "Python syntax: variables, lists, dicts, sets, tuples",
            "Functions, closures, decorators and generators",
            "NumPy: arrays, broadcasting, vectorised operations",
            "Pandas: DataFrames, filtering, groupby, merge, pivot",
            "Matplotlib & Seaborn: charts, subplots, heatmaps",
            "File I/O: CSV, JSON, parquet, API responses",
            "Virtual environments and pip dependency management",
            "Jupyter notebooks and Google Colab setup",
          ],
          tools: ["Python 3.11", "NumPy", "Pandas", "Matplotlib", "Jupyter", "VS Code"],
          lab: "Build a data analysis pipeline processing 50,000 rows of real e-commerce data — clean, enrich, visualise and export insights",
          labOutcome: "A reproducible Jupyter notebook with 10 business insights and charts ready for a data science portfolio",
        },
        {
          title: "Machine Learning Foundations",
          week: "Week 2",
          topics: [
            "Supervised vs unsupervised vs reinforcement learning",
            "Regression: linear, polynomial, ridge, lasso",
            "Classification: logistic regression, decision trees, random forest",
            "Feature engineering: encoding, scaling, selection",
            "Train/test split, cross-validation, hyperparameter tuning",
            "scikit-learn Pipelines: preprocessing + model in one object",
            "Model evaluation: accuracy, F1, ROC-AUC, confusion matrix",
            "Overfitting, underfitting, bias-variance tradeoff",
          ],
          tools: ["scikit-learn", "XGBoost", "Pandas", "Matplotlib"],
          lab: "Build and evaluate a customer churn prediction model — feature engineering, model selection, tuning and a web demo",
          labOutcome: "Deployed churn model achieving >85% accuracy with explainability via SHAP values",
        },
        {
          title: "Neural Networks & Deep Learning",
          week: "Week 3–4",
          topics: [
            "Perceptrons, layers, activation functions (ReLU, sigmoid, softmax, GELU)",
            "Forward propagation and backpropagation (chain rule intuition)",
            "Loss functions: MSE, cross-entropy, BCE",
            "Optimisers: SGD, Adam, AdamW — learning rate schedulers",
            "Batch normalisation, dropout, weight decay",
            "TensorFlow/Keras: Sequential and Functional API",
            "CNNs: convolutional layers, pooling, ResNet architecture",
            "Transfer learning: fine-tune ImageNet models",
            "GPU training setup: CUDA, Google Colab T4/A100",
          ],
          tools: ["TensorFlow", "Keras", "PyTorch", "Google Colab", "Weights & Biases"],
          lab: "Train an image classification model on a real dataset — fine-tune ResNet50 to 92%+ accuracy and deploy as a REST API",
          labOutcome: "A served image classifier with <200ms inference time, documented model card, and W&B experiment tracking",
        },
      ],
      capstone: {
        title: "Phase 1 Capstone — AI Data Pipeline",
        deliverables: [
          "Automated data ingestion + cleaning pipeline",
          "EDA notebook with 15+ visualisations",
          "Trained ML classification model (>85% accuracy)",
          "Model served as FastAPI endpoint",
          "GitHub repo with README and Docker setup",
        ],
      },
    },
    {
      label: "Phase 2",
      title: "Prompt Engineering & LLMs",
      duration: "4 Weeks",
      color: "bg-[#F0FDF4] text-[#166534] border-[#BBF7D0]",
      icon: Sparkles,
      objective:
        "Master the art and science of working with Large Language Models. Learn how to engineer prompts, consume LLM APIs, and build AI-powered applications using OpenAI, Claude, and Azure OpenAI — skills hiring for in 2025.",
      modules: [
        {
          title: "LLM Architecture & API Consumption",
          week: "Week 5",
          topics: [
            "Transformer architecture: attention, self-attention, multi-head attention (conceptual)",
            "GPT-5.5, Claude Opus 4.8, Gemini 3 Pro, DeepSeek V4 Pro, Llama 4 — capability comparison (May 2026)",
            "OpenAI API: chat completions, streaming, vision, function calling",
            "Azure OpenAI Service: deployment, API version management",
            "Token economics: counting tokens, context windows, cost optimisation",
            "Temperature, top-p, frequency/presence penalty — when to tune each",
            "JSON mode, structured outputs and response_format",
            "Rate limiting, retry logic and error handling in production",
          ],
          tools: ["OpenAI API", "Azure OpenAI", "Python openai SDK", "tiktoken"],
          lab: "Build an AI Q&A bot with streaming responses, token cost tracking and automatic retry on rate limits",
          labOutcome: "Production-quality LLM wrapper with cost dashboard showing spend per session",
        },
        {
          title: "Prompt Engineering Techniques",
          week: "Week 6",
          topics: [
            "Zero-shot, one-shot and few-shot prompting",
            "Chain-of-thought (CoT): standard and zero-shot CoT",
            "Tree-of-Thought (ToT) for multi-step reasoning",
            "ReAct prompting: Reasoning + Acting pattern",
            "Role prompting and system message design for consistent personas",
            "Structured output generation: JSON, XML, markdown tables",
            "Prompt templating with Jinja2 and f-strings",
            "Prompt versioning, evaluation and A/B testing strategies",
          ],
          tools: ["OpenAI Playground", "LangSmith", "PromptLayer"],
          lab: "Engineer a prompt system for a document summarisation service — measure quality with ROUGE scores and human eval",
          labOutcome: "A/B tested prompt system with documented evaluation showing 40% quality improvement over baseline",
        },
        {
          title: "LangChain Fundamentals",
          week: "Week 7–8",
          topics: [
            "LangChain architecture: Chains, Runnables (LCEL), Components",
            "PromptTemplate, ChatPromptTemplate, MessagesPlaceholder",
            "Output parsers: PydanticOutputParser, StructuredOutputParser",
            "Document loaders: PDF, CSV, web, Notion, Google Drive",
            "Text splitters: RecursiveCharacterTextSplitter, semantic chunking",
            "Memory: ConversationBufferMemory, SummaryMemory, EntityMemory",
            "Sequential chains and branching with RunnableBranch",
            "LangSmith: tracing, evaluation, dataset management",
          ],
          tools: ["LangChain", "LangSmith", "PyPDF", "BeautifulSoup"],
          lab: "Build a multi-turn document Q&A application with conversation memory and LangSmith tracing for debugging",
          labOutcome: "A conversational document assistant that remembers context across 10+ turns with full trace visibility",
        },
      ],
      capstone: {
        title: "Phase 2 Capstone — AI Customer Support System",
        deliverables: [
          "Multi-turn conversational bot with memory",
          "Custom system prompt with role and constraint engineering",
          "Structured JSON output parsing with validation",
          "FastAPI REST endpoint with Swagger docs",
          "LangSmith tracing dashboard for all conversations",
        ],
      },
    },
    {
      label: "Phase 3",
      title: "Generative AI & RAG Systems",
      duration: "6 Weeks",
      color: "bg-[#FFF7ED] text-[#9A3412] border-[#FED7AA]",
      icon: Bot,
      objective:
        "Build production-grade Retrieval Augmented Generation (RAG) systems. Master vector databases, embedding models, advanced retrieval strategies and evaluation frameworks used by top AI engineering teams.",
      modules: [
        {
          title: "Vector Databases & Embeddings",
          week: "Week 9",
          topics: [
            "What are embeddings — semantic meaning in vector space",
            "OpenAI text-embedding-3-small/large, Cohere embed-v3, BGE, E5",
            "Cosine similarity, dot product and L2 distance for nearest-neighbour search",
            "Pinecone: namespaces, metadata filtering, sparse-dense hybrid search",
            "ChromaDB: local vector store, persistence, collection management",
            "Qdrant: payload filtering, on-disk storage, batch upsert",
            "Weaviate: GraphQL interface, hybrid BM25+dense search",
            "FAISS: flat, IVFFlat, HNSW index types — performance tradeoffs",
          ],
          tools: ["Pinecone", "ChromaDB", "Qdrant", "FAISS", "OpenAI Embeddings"],
          lab: "Build a semantic search engine over 10,000+ Stack Overflow answers — compare retrieval quality across 4 vector databases",
          labOutcome: "Semantic search with <200ms p99 latency, MRR@10 metric tracking, and comparison dashboard",
        },
        {
          title: "RAG Pipeline Architecture",
          week: "Week 10–11",
          topics: [
            "Naive RAG vs Advanced RAG vs Modular RAG — evolution and tradeoffs",
            "Document indexing pipeline: load → split → embed → store",
            "Chunking strategies: fixed-size, recursive, semantic, parent-child",
            "Hybrid search: BM25 + dense embeddings weighted combination",
            "Re-ranking: Cohere Rerank, cross-encoder models, ColBERT",
            "Context window management: lost-in-the-middle problem solutions",
            "Query transformation: HyDE, step-back prompting, multi-query",
            "Citation and source attribution in generated answers",
            "Hallucination detection and grounding techniques",
          ],
          tools: ["LangChain", "LlamaIndex", "Cohere Rerank", "BM25Okapi"],
          lab: "Build a production RAG system over a 500-page technical manual — implement hybrid search, re-ranking and citation extraction",
          labOutcome: "RAG system with source-cited answers, faithfulness >0.85 and context relevance >0.80 measured by RAGAS",
        },
        {
          title: "LlamaIndex & Advanced RAG",
          week: "Week 12",
          topics: [
            "LlamaIndex vs LangChain — architecture comparison and when to use each",
            "VectorStoreIndex, SummaryIndex, KnowledgeGraphIndex",
            "Query engines: VectorStoreQueryEngine, RouterQueryEngine",
            "Sub-question decomposition for complex multi-hop questions",
            "Recursive retrieval and parent-document retrieval",
            "RAGAS evaluation: faithfulness, context recall, answer correctness",
            "Streaming RAG responses with async generators",
            "Multi-modal RAG: images + text in a single pipeline",
          ],
          tools: ["LlamaIndex", "RAGAS", "OpenAI GPT-5.5", "Weaviate"],
          lab: "Build an advanced multi-document research assistant with RAGAS evaluation and a Streamlit dashboard showing live metrics",
          labOutcome: "Multi-document RAG with automatic quality regression alerts when faithfulness drops below threshold",
        },
        {
          title: "Multimodal AI & Image Generation",
          week: "Week 13",
          topics: [
            "GPT-5.5 vision: image analysis, OCR, chart reading",
            "Claude Opus 4.8 vision capabilities and use cases",
            "DALL-E 3 and Stable Diffusion XL for image generation",
            "Whisper API for speech-to-text (multilingual, timestamps)",
            "TTS-1 and TTS-1-HD for natural text-to-speech",
            "Building multimodal pipelines: audio → text → image → text",
            "Invoice and document extraction with vision models",
            "Cost and quality tradeoffs in multimodal applications",
          ],
          tools: ["GPT-5.5", "DALL-E 3", "Whisper", "OpenAI TTS", "Streamlit"],
          lab: "Build a multimodal AI assistant that extracts data from invoice images, validates figures and exports to CSV automatically",
          labOutcome: "Invoice processor with >95% field extraction accuracy on real-world documents",
        },
      ],
      capstone: {
        title: "Phase 3 Capstone — Enterprise Knowledge Base",
        deliverables: [
          "Vector database with 10,000+ indexed documents",
          "Hybrid search with BM25 + dense + re-ranking",
          "Source-cited Q&A with RAGAS evaluation dashboard",
          "Multi-modal support (PDF + images)",
          "FastAPI backend + React frontend deployed on cloud",
        ],
      },
    },
    {
      label: "Phase 4",
      title: "AI Agents & Production Deployment",
      duration: "6 Weeks",
      color: "bg-[#F0F9FF] text-[#0C4A6E] border-[#BAE6FD]",
      icon: Cpu,
      objective:
        "Build autonomous AI agents and deploy production-grade AI applications. Learn multi-agent orchestration, tool use, and how to monitor and maintain AI systems in production — the skills that differentiate senior AI engineers.",
      modules: [
        {
          title: "AI Agents & Tool Use",
          week: "Week 14–15",
          topics: [
            "What are AI agents — the ReAct (Reason + Act) framework",
            "Function calling: tool definitions, parameter schemas, required/optional",
            "Parallel function calling and multi-step tool use",
            "Building custom tools: web search, calculator, database, file system",
            "LangChain AgentExecutor and the new LangGraph framework",
            "Agent memory: short-term (conversation), long-term (vector store)",
            "Planning: task decomposition, sub-task generation",
            "Agent evaluation: task success rate, tool efficiency, cost per task",
          ],
          tools: ["LangChain Agents", "LangGraph", "OpenAI Function Calling", "Tavily Search"],
          lab: "Build an AI research agent that browses 10 websites, extracts information, deduplicates and writes a structured 2-page report",
          labOutcome: "Autonomous research agent completing tasks 10× faster than manual browsing with citation accuracy >90%",
        },
        {
          title: "Multi-Agent Systems",
          week: "Week 16",
          topics: [
            "Multi-agent orchestration: why single agents fail at complex tasks",
            "CrewAI: agents, tasks, tools, crews and processes (sequential/hierarchical)",
            "AutoGen: conversable agents, GroupChat, human-in-the-loop",
            "Agent roles: planner, executor, critic, memory manager",
            "Communication patterns: broadcast, round-robin, directed",
            "Guardrails: input validation, output filtering, safety checks",
            "Debugging multi-agent pipelines with LangSmith traces",
            "Evaluating multi-agent quality and cost efficiency",
          ],
          tools: ["CrewAI", "AutoGen", "LangSmith", "LangGraph"],
          lab: "Build a 3-agent content system (researcher + writer + editor) that produces a 1,000-word SEO article from a single keyword",
          labOutcome: "Multi-agent content pipeline producing publish-ready articles in under 3 minutes",
        },
        {
          title: "Production AI Deployment",
          week: "Week 17–18",
          topics: [
            "FastAPI for AI APIs: async endpoints, dependency injection, middleware",
            "Pydantic v2: strict validation, custom validators, serialisation",
            "Docker containerisation for AI apps: GPU support, model caching",
            "Environment management: secrets, API keys, .env files",
            "Rate limiting and cost control: per-user token quotas",
            "Background task processing with Celery and Redis",
            "Deploying to Azure App Service, AWS Lambda, and Google Cloud Run",
            "GitHub Actions CI/CD for AI application deployment",
          ],
          tools: ["FastAPI", "Docker", "Celery", "Redis", "GitHub Actions", "Azure App Service"],
          lab: "Containerise and deploy a RAG application to Azure — with CI/CD pipeline, health checks and auto-scaling",
          labOutcome: "Live AI application URL with CI/CD: every git push auto-deploys to production in under 4 minutes",
        },
        {
          title: "AI Monitoring, Evaluation & LangSmith",
          week: "Week 19–20",
          topics: [
            "LLM observability: why traditional monitoring is not enough",
            "LangSmith: project setup, trace collection, run filtering",
            "LangSmith Evaluation: dataset creation, evaluators (correctness, toxicity)",
            "A/B testing prompts: statistical significance, sample size calculation",
            "Cost tracking: per-model, per-user, per-feature dashboards",
            "Latency monitoring: p50/p95/p99, timeout budgets",
            "Guardrails AI: input/output validation, sensitive data masking",
            "AI application logging best practices for compliance and debugging",
          ],
          tools: ["LangSmith", "Guardrails AI", "OpenTelemetry", "Grafana", "Prometheus"],
          lab: "Set up full LangSmith observability + Grafana dashboards for a production RAG app — detect and fix a performance regression",
          labOutcome: "Operational AI monitoring: automated alerts when quality drops, with runbook to investigate and fix",
        },
      ],
      capstone: {
        title: "Final Capstone — Production AI SaaS Application",
        deliverables: [
          "Multi-agent AI workflow (3+ agents: planner + executor + reviewer)",
          "Production RAG + agent combined system",
          "Dockerised FastAPI backend with authentication",
          "CI/CD deployed on Azure or AWS",
          "LangSmith monitoring with cost and quality dashboards",
          "GitHub portfolio-ready repository with README, demo video",
        ],
      },
    },
  ],

  bonusTracks: [
    {
      icon: Terminal,
      title: "SQL & Data Engineering Basics",
      topics: ["PostgreSQL fundamentals", "Joins, CTEs and window functions", "SQLAlchemy ORM", "Data modelling for AI apps", "ETL pipeline concepts"],
    },
    {
      icon: Sparkles,
      title: "AI Product & UX Design",
      topics: ["Building AI product specs", "Prompt UX patterns", "Evaluating LLM quality", "AI product roadmapping", "Responsible AI principles"],
    },
    {
      icon: Bot,
      title: "Interview Preparation",
      topics: ["100+ AI engineering interview questions", "System design for LLM apps", "LLM evaluation scenarios", "Mock technical interviews + feedback", "Resume and GitHub portfolio review"],
    },
  ],

  projects: [
    { title: "AI Customer Support Bot",        desc: "Multi-turn conversational bot using GPT-5.5 with memory, custom system prompt and LangSmith tracing" },
    { title: "PDF Intelligence Platform",      desc: "RAG-powered Q&A over PDF documents — hybrid search, re-ranking, source citations and RAGAS evaluation" },
    { title: "AI Research Agent",             desc: "Autonomous ReAct agent that browses the web, deduplicates findings and writes structured research reports" },
    { title: "Semantic Search Engine",        desc: "Vector-based search over 10,000+ documents — OpenAI embeddings + Pinecone with BM25 hybrid retrieval" },
    { title: "AI Resume Analyser",            desc: "GPT-5.5 Vision parses resumes, scores candidates against job descriptions and generates interview questions" },
    { title: "Multi-Agent Content System",    desc: "CrewAI 3-agent pipeline: researcher → writer → editor producing SEO-optimised content in 3 minutes" },
    { title: "Voice AI Assistant",            desc: "Whisper speech-to-text → GPT-5.5 reasoning → TTS-1 speech synthesis — fully conversational voice bot" },
    { title: "Enterprise Knowledge Base",     desc: "Company document RAG with Entra ID access control, department routing, and RAGAS quality monitoring" },
    { title: "AI Invoice Processor",          desc: "GPT-5.5 Vision extracts fields from scanned invoices with >95% accuracy and auto-exports to Google Sheets" },
    { title: "LLM Cost & Quality Dashboard",  desc: "Real-time LangSmith + Grafana dashboard: cost per session, latency, faithfulness scores, A/B test results" },
    { title: "AI Code Review Bot",            desc: "GitHub Actions workflow: AI reviews every PR — suggests improvements, detects bugs, posts inline comments" },
    { title: "Deployed AI SaaS Application",  desc: "Full-stack FastAPI + React app containerised with Docker, deployed to Azure, with CI/CD and monitoring" },
  ],

  technologies: [
    "Python 3.11", "OpenAI GPT-5.5", "Claude Opus 4.8", "Gemini 3 Pro", "DeepSeek V4", "LangChain", "LlamaIndex",
    "LangSmith", "Pinecone", "ChromaDB", "Qdrant", "FAISS", "FastAPI", "Docker",
    "Hugging Face", "CrewAI", "AutoGen", "LangGraph", "RAGAS", "Azure OpenAI",
    "Whisper", "DALL-E 3", "Guardrails AI", "Redis", "GitHub Actions",
  ],

  certifications: [
    { code: "OpenAI Developer",   title: "OpenAI API Developer Certification (prep)", emoji: "🤖" },
    { code: "Google Cloud AI",    title: "Professional ML Engineer (prep)",            emoji: "🧠" },
    { code: "AWS CLF-C02",       title: "AWS Cloud Practitioner (optional add-on)",   emoji: "☁️" },
  ],

  careerTiers: [
    { level: "Entry-Level (0–1 yr) · ₹4–8 LPA",    roles: ["Junior AI Engineer", "Prompt Engineer", "AI Application Developer", "ML Operations Analyst"],               color: "border-[#BFDBFE] bg-[#EFF6FF]" },
    { level: "Mid-Level (1–3 yr) · ₹10–18 LPA",    roles: ["AI Engineer", "Generative AI Developer", "LLM Application Engineer", "AI Solutions Architect"],             color: "border-[#BBF7D0] bg-[#F0FDF4]" },
    { level: "Advanced (3+ yr) · ₹20–40 LPA",      roles: ["AI Platform Engineer", "Head of AI Engineering", "AI Product Lead", "GenAI Consultant"],                    color: "border-[#FED7AA] bg-[#FFF7ED]" },
  ],

  idealFor: [
    { icon: GraduationCap, title: "Students & Fresh Graduates", desc: "Enter the fastest-growing tech field with 12 real AI projects. No prior ML or AI experience needed.", color: "text-[#4F46E5]", bg: "bg-[#EEF2FF]" },
    { icon: Briefcase,     title: "Software Developers",        desc: "Add LLM, RAG and AI agent skills on top of your existing programming background. Commands a 40–60% salary jump.", color: "text-[#059669]", bg: "bg-[#ECFDF5]" },
    { icon: Users2,        title: "Business & Product Professionals", desc: "Understand how to build, evaluate and deploy AI products. Bridge the gap between business needs and AI engineering.", color: "text-[#D97706]", bg: "bg-[#FFFBEB]" },
  ],

  faqs: [
    { q: "Do I need programming experience to join?", a: "Basic Python knowledge helps but is not required. Week 1 covers Python from scratch. If you can write a for-loop in any language, you'll be fine." },
    { q: "Which AI models and APIs will I use?", a: "Primarily OpenAI (GPT-5.5, embeddings, DALL-E 3, Whisper) and Azure OpenAI. We also cover Claude Opus 4.8, Gemini 3 Pro, DeepSeek V4 and open-source models (Llama 4, Mistral 3) for cost-effective alternatives." },
    { q: "How much will API costs be during the program?", a: "Estimated ₹800–1,500 over 5 months using OpenAI credits. We teach cost-optimisation from week 1 so you always know what you're spending. OpenAI's $5 free credit covers the first 2 weeks." },
    { q: "What makes this different from a YouTube course or Udemy?", a: "Live mentor sessions, real project reviews, doubt-clearing sessions, mock interviews, portfolio guidance and placement support. YouTube teaches you to watch; we teach you to build and get hired." },
    { q: "Can I take this alongside a full-time job?", a: "Yes — weekend batches are available. Plan for 15–18 hours/week: 3h live sessions + 5h self-paced LMS + 7h labs. Many of our learners are working professionals." },
  ],
};

export default function AiGenerativeAiMasterProgramPage() {
  return <ProgramPageLayout data={data} />;
}
